
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if(vexRT[4] > 20)
		{
			motor[left] = vexRT[4];
			motor[right] = 0;
		}

		if(vexRT[4] < -20)
		{
			motor[right] = vexRT[4]*-1;
			motor[left] = 0;
		}


			motor[right] = vexRT[3];
			motor[left] = vexRT[3];


	}
}
